/**
 * @File Name          : MyCustomTestClass.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 28/6/2020, 3:12:11 pm
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    28/6/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/

public with sharing class MyCustomTestClass {
    public MyCustomTestClass() {
        System.debug('my class');
    }
}