/*************************************************************************************************************
 * @name            Test123
 * @author          Rohit <test.com>
 * @created         23 / 06 / 2020
 * @description     Test VS code
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *              No.     Date            Author                  Description
 *              ----    ------------    --------------------    ----------------------------------------------
 * @version     1.0     2020-06-23      Rohit                   Changes desription
 *
**************************************************************************************************************/
public with sharing class Test123 {
    public Test123() {

    }

    /*********************************************************************************************************
     * @name            The name of your class or method
     * @author          Your name <email@email.com>
     * @created         23 / 06 / 2020
     * @description     Description of your code
     * @param           String param : Explanation
     * @return          Explanation of the return value
    **********************************************************************************************************/
    public static void myTestMethod(){
        
        system.debug('edited from salesforce');
    }
}